<?php
/**
 * Created by PhpStorm.
 * User: glen9
 * Date: 2018/10/12
 * Time: 11:17
 */

namespace app\admin\model;
use think\Model;

class Matchfinance extends Model
{

    // 表名
    protected $name = 'sales_order';
    protected $model = null;
    /**
     * 获取原始方案数据
     * @param $ids 订单Id
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = model('SalesOrder');
    }

    private static function getOriginalPlan($ids){

    }

    public  function bigdata(){

        return $this->hasOne('BigData','sales_order_id','id',[],'LEFT');
    }
}