<?php

return array (
  'name' => '君忆之家CRM',
  'beian' => ' 蜀 ICP备 17036095号',
  'cdnurl' => '',
  'version' => '1.8.6',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
    'message' => '员工权限配置',
    'integral' => '积分管理',
    'share' => '小程序分享配置',
    'companystore' => '门店',
    'coupon' => '优惠券',
    'prize' => '大转盘抽奖配置',
    'activity' => '活动中心',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.mxhichina.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => 'operate@aicheyide.com',
  'mail_smtp_pass' => 'Xrzl2018',
  'mail_verify_type' => '2',
  'mail_from' => 'operate@aicheyide.com',
  'pushMessage' => 
  array (
    'message1' => '总经理',
    'message2' => '财务经理',
    'message3' => '销售经理',
    'message8' => '销售顾问',
    'message13' => '内勤',
    'message5' => '人事经理',
    'message6' => '推广',
    'message7' => '风控主管（征信审核）',
    'message10' => '请款审核（财务）',
    'message11' => '方案管理（财务）',
    'message12' => '月供管理（财务）',
    'message14' => '新车管理',
    'message15' => '租车管理',
    'message16' => '保险管理',
    'message17' => '资料报表管理',
    'message18' => '修理厂维护',
    'message19' => '行政',
    'message21' => '超级管理员',
    'message25' => '客服',
    'message26' => '财务（出纳）',
    'message27' => '金融按揭专员',
    'message28' => '渠道',
    'message29' => '南充分公司',
    'message30' => '西安分公司',
    'message31' => '银川分公司',
    'message32' => '昆明分公司',
    'message33' => '（渠道）',
    'message34' => '石河子分公司',
  ),
  'integral' => 
  array (
    'fabulous' => '1',
    'share' => '5',
    'sign' => '2',
  ),
  'share' => 
  array (
    'index_share_title' => '新车千元开回家！！！',
  ),
  'company' => '/uploads/20181217/0b2b4fae5709a93da400c3c7ca252529.jpg',
  'coupon' => '0',
  'index_share_img' => '/uploads/20190102/e41a9328165ab7f9dfa6832dd1a5eb70.png',
  'share_moments_bk_img' => '/uploads/20190102/cf67fd6abe715b101e040a1a0a649f8d.png',
  'index_share_bk_qrcode' => '/uploads/20181217/54e6ec10decba4c666da67341e543b58.jpg',
  'starttime' => '2018-12-20 15:59:34',
  'endtime' => '2019-01-01 00:00:00',
  'zhuanpan' => '/uploads/20181225/06d902d6f2dca23bb0877520b69d56a2.png',
);